# Generated by Django 2.2.4 on 2020-11-17 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='t_festival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=255)),
                ('rocnik', models.SmallIntegerField()),
                ('zaciatok', models.DateField()),
                ('koniec', models.DateField()),
                ('miesto', models.CharField(max_length=255)),
                ('kapacite', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='t_interpret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=255)),
                ('datum_vzniku', models.DateField()),
                ('clenovia', models.TextField()),
                ('albumy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='t_uzivatel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('meno', models.CharField(max_length=255)),
                ('priezvisko', models.CharField(max_length=255)),
                ('heslo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='t_stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov', models.CharField(max_length=255)),
                ('plocha', models.PositiveIntegerField()),
                ('festival_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_festival')),
            ],
        ),
        migrations.CreateModel(
            name='t_rezervacia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.SmallIntegerField()),
                ('cena', models.SmallIntegerField()),
                ('stav', models.SmallIntegerField()),
                ('majitel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_uzivatel')),
            ],
        ),
        migrations.CreateModel(
            name='r_vystupuje_na',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zaciatok', models.DateTimeField()),
                ('koniec', models.DateTimeField()),
                ('id_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_stage')),
            ],
        ),
        migrations.CreateModel(
            name='r_rezervacia_na',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rezervacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_rezervacia')),
                ('id_uzivatela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_uzivatel')),
            ],
        ),
    ]
