# Generated by Django 2.2.4 on 2020-11-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_festival',
            old_name='kapacite',
            new_name='kapacita',
        ),
        migrations.AlterField(
            model_name='t_interpret',
            name='albumy',
            field=models.TextField(blank=True),
        ),
    ]
