# Generated by Django 2.2.4 on 2020-11-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_auto_20201119_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='r_zucastni_sa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_festival')),
                ('id_interpret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_interpret')),
            ],
        ),
    ]
