# Generated by Django 3.1.3 on 2020-11-23 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_festival',
            name='vytvoril',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.t_uzivatel'),
            preserve_default=False,
        ),
    ]
