# Generated by Django 3.1.3 on 2020-11-23 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_auto_20201123_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='t_festival',
            options={'permissions': [('edit_festival', 'Can create, edit and delete festivals')]},
        ),
        migrations.AlterModelOptions(
            name='t_interpret',
            options={'permissions': [('edit_interpret', 'Can create, edit and delete inteprets')]},
        ),
        migrations.AlterModelOptions(
            name='t_stage',
            options={'permissions': [('edit_stage', 'Can create, edit and delete stages')]},
        ),
    ]
