# Generated by Django 3.1.3 on 2020-11-24 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0008_auto_20201123_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='r_rezervacia_na',
            name='id_uzivatela',
        ),
        migrations.RemoveField(
            model_name='t_rezervacia',
            name='cena',
        ),
        migrations.RemoveField(
            model_name='t_rezervacia',
            name='typ',
        ),
        migrations.RemoveField(
            model_name='t_stage',
            name='plocha',
        ),
        migrations.AddField(
            model_name='t_festival',
            name='obrazok',
            field=models.ImageField(default=None, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_festival',
            name='popis',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='t_stage',
            name='popis',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='t_listok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.SmallIntegerField()),
                ('cena', models.SmallIntegerField()),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='festivals.t_festival')),
            ],
        ),
        migrations.AddField(
            model_name='r_rezervacia_na',
            name='id_listku',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='festivals.t_listok'),
            preserve_default=False,
        ),
    ]
