# Generated by Django 3.1.3 on 2020-11-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0010_auto_20201125_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='t_listok',
            old_name='festival',
            new_name='id_festival',
        ),
    ]
