# Generated by Django 3.1.3 on 2020-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0011_auto_20201125_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_listok',
            name='popis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='t_listok',
            name='typ',
            field=models.CharField(max_length=10),
        ),
    ]
