# Generated by Django 3.1.3 on 2020-11-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0012_auto_20201125_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_listok',
            name='pocet',
            field=models.SmallIntegerField(default=200),
            preserve_default=False,
        ),
    ]
