# Generated by Django 3.1.3 on 2020-11-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0013_t_listok_pocet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_rezervacia',
            name='stav',
            field=models.CharField(max_length=50),
        ),
    ]
