# Generated by Django 3.1.3 on 2020-11-26 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0014_auto_20201125_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_rezervacia',
            name='email',
            field=models.EmailField(default='hidden@user.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='t_rezervacia',
            name='majitel',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
