# Generated by Django 3.1.3 on 2020-11-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0016_auto_20201127_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_festival',
            name='obrazok',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
