# Generated by Django 3.1.3 on 2020-11-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0018_auto_20201127_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_festival',
            name='obrazok',
            field=models.CharField(default='https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80', max_length=255),
        ),
    ]
