# Generated by Django 3.1.3 on 2020-11-27 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('festivals', '0019_auto_20201127_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_rezervacia',
            name='majitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
