# Generated by Django 3.1.3 on 2020-11-28 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0020_auto_20201127_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_vystupuje_na',
            name='id_interpret',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='festivals.t_interpret'),
            preserve_default=False,
        ),
    ]
